/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountPopover: typeof import('./src/components/AccountPopover.vue')['default']
    AppIndividualization: typeof import('./src/components/AppIndividualization.vue')['default']
    AppNotification: typeof import('./src/components/AppNotification.vue')['default']
    AppTheme: typeof import('./src/components/AppTheme.vue')['default']
    Drawer: typeof import('./src/components/notification/Drawer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    List: typeof import('./src/components/notification/List.vue')['default']
    Logo: typeof import('./src/components/learn-once/Logo.vue')['default']
    Menubar: typeof import('./src/components/layout/Menubar.vue')['default']
    MenubarDrawer: typeof import('./src/components/layout/MenubarDrawer.vue')['default']
    MenubarToggle: typeof import('./src/components/layout/MenubarToggle.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
    TabBarItem: typeof import('./src/components/layout/TabBarItem.vue')['default']
    UpdateLog: typeof import('./src/components/learn-once/UpdateLog.vue')['default']
    Welcome: typeof import('./src/components/learn-once/Welcome.vue')['default']
  }
}
